#!/usr/bin/env python3
"""
Renders "FLOCKVIEW" in a pixel/bitmap font for the Flipper Zero 128x64 screen.
Hacker/terminal aesthetic — blocky, crisp, 1-bit, no anti-aliasing.
Target canvas: 112x28 px (drawn at x=8, y=5 on screen).
"""

from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
import sys

ROOT    = Path(__file__).resolve().parents[1]
OUT_H   = ROOT / "flockview_ascii_logo.h"
OUT_PNG = ROOT / "assets" / "flockview_ascii_logo_112x28.png"

TARGET_W, TARGET_H = 112, 28
TEXT = "FLOCKVIEW"

# ── 1. Font priority: pixel fonts first, then system fallbacks ────────────────
ASSETS = ROOT / "assets"
FONT_CANDIDATES = [
    str(ASSETS / "PressStart2P-Regular.ttf"),   # 8-bit arcade pixel font
    str(ASSETS / "Silkscreen-Regular.ttf"),      # clean pixel font
    "/System/Library/Fonts/Monaco.ttf",          # macOS monospaced fallback
    "/System/Library/Fonts/Supplemental/Courier New.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf",
]

font_path = None
for p in FONT_CANDIDATES:
    if Path(p).exists():
        font_path = p
        print(f"Using font: {p}")
        break

if font_path is None:
    print("ERROR: No font found.")
    sys.exit(1)

# ── 2. Find largest size that fits ────────────────────────────────────────────
best_font = None
best_size = None
best_bbox = None

for size in range(60, 3, -1):
    try:
        font = ImageFont.truetype(font_path, size)
    except Exception:
        continue

    probe = Image.new("L", (1, 1), 255)
    d     = ImageDraw.Draw(probe)
    bbox  = d.textbbox((0, 0), TEXT, font=font)
    w = bbox[2] - bbox[0]
    h = bbox[3] - bbox[1]

    if w <= TARGET_W - 2 and h <= TARGET_H - 2:
        best_font = font
        best_size = size
        best_bbox = bbox
        print(f"Best fit: size={size}px → '{TEXT}' is {w}×{h}px in {TARGET_W}×{TARGET_H}")
        break

if best_font is None:
    print("ERROR: Could not fit text at any size.")
    sys.exit(1)

# ── 3. Render centered, hard threshold — NO anti-aliasing ─────────────────────
img = Image.new("L", (TARGET_W, TARGET_H), 255)
d   = ImageDraw.Draw(img)

bx0, by0, bx1, by1 = best_bbox
text_w = bx1 - bx0
text_h = by1 - by0

ox = (TARGET_W - text_w) // 2 - bx0
oy = (TARGET_H - text_h) // 2 - by0

d.text((ox, oy), TEXT, font=best_font, fill=0)

# Hard threshold — pixel fonts need 200 (not 128) because their anti-aliasing
# is very light; we want pure black pixels only
mono = img.point(lambda p: 255 if p < 200 else 0)

# ── 4. Preview PNG on Flipper amber background ────────────────────────────────
preview = Image.new("RGB", (TARGET_W, TARGET_H), (235, 145, 30))
pix = preview.load()
mono_arr = list(mono.getdata())
for y in range(TARGET_H):
    for x in range(TARGET_W):
        if mono_arr[y * TARGET_W + x] == 255:
            pix[x, y] = (22, 22, 22)
preview.save(OUT_PNG)
print(f"Wrote preview: {OUT_PNG}")

# ── 5. XBM encode (LSB-first per row) ────────────────────────────────────────
bytes_per_row = (TARGET_W + 7) // 8
data = []
for y in range(TARGET_H):
    for byte_index in range(bytes_per_row):
        b = 0
        for bit in range(8):
            x = byte_index * 8 + bit
            if x < TARGET_W and mono_arr[y * TARGET_W + x] == 255:
                b |= (1 << bit)
        data.append(b)

chunks = []
for i in range(0, len(data), 14):
    chunks.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i+14]) + ",")

OUT_H.write_text(f'''#pragma once

#include <stdint.h>

#define FLOCKVIEW_ASCII_LOGO_WIDTH  {TARGET_W}
#define FLOCKVIEW_ASCII_LOGO_HEIGHT {TARGET_H}

// Generated by tools/render_logo.py
// "{TEXT}" in pixel font at size {best_size}px, centered in {TARGET_W}x{TARGET_H}.
static const uint8_t FLOCKVIEW_ASCII_LOGO_112X28[] = {{
{chr(10).join(chunks)}
}};
''')
print(f"Wrote header: {OUT_H}")
